### PR TITLE
Add comparative benchmark

### PR DESCRIPTION
**Pull request by vassudanagunta**
`licofi` is the fastest by far of 9 Javascript line/column indexers, as the results of this submitted comparative benchmark program show below. Yet `licofi` has near zero usage.  Many projects demanding speed would consider switching to licofi if this information was made available.
| package            |     speed (ops/sec) | npm downloads per week |
| ------------------ | ---------: | ---------------------: |
| find-line-column   |     11,565 |                 61,000 |
| simple-text-buffer |    118,135 |                    159 |
| char-props         |    582,859 |                 16,000 |
| string-pos         |  2,903,177 |                     17 |
| vfile-location     |  1,451,754 |              2,800,000 |
| lines-and-columns  |  1,571,599 |              6,500,000 |
| vscode-textbuffer  |  8,252,509 |                  8,000 |
| line-column        | 22,269,372 |                 20,000 |
| **licofi**             |  😍  31,663,220 |             🤔         1 |

I wrote this comparative benchmark in my hunt for the fastest line/column indexer.  I originally modified of @danielkalen's [string-pos](https://github.com/danielkalen/string-pos) benchmark, correcting a serious flaw that produced very misleading results (and thus a false claim of being the fastest). That PR (danielkalen/string-pos#1) has not been accepted 3 months after having been acknowledged as correct. So I decided to rewrite it from the ground up, and submit it to the fastest of the bunch, `licofi`. 

The benchmark is in its own `bench` subdirectory with its own `package.json` to minimize impact on the existing project. I used regular Javascript rather than Typescript also to avoid impacting the main project and avoid transpiling benchmark code to the `dist` directory.  (I could use `ts-node` if TS is strongly preferred. let me know.)

The benchmark tests four different input text sizes. Below are the results on my 8 year-old MacBook Air:

bench comparison

### CODE REVIEW

**Comment by vneenz** [comment]
Thank you for the contribution! This is awesome work. I'll be adding this information to the readme shortly.

**Comment by vassudanagunta** [comment]
My pleasure.

You might also want to inform the big users of `lines-and-columns` and `vfile-location`. You can find them under Dependents in their npmjs.com listing -- there are some popular libraries in there. You can just point them at the benchmark results. Or if you were especially motivated, submit a PR substituting `licofi` for their existing indexer and showing them how *their* code got faster.

**Comment by vassudanagunta** [comment]
I'd include a link on your README to the full range of benchmarks across file sizes because the typical file size for many applications can be medium or even small. Let them see all the data so they can make intelligent decisions. :)

**Comment by vassudanagunta** [comment]
What I haven't done is look at memory usage. Is `licofi` so much faster because it trades memory for speed? I don't have time to look into it, but that's a question.

**Comment by vneenz** [comment]
> 
> 
> I'd include a link on your README to the full range of benchmarks across file sizes because the typical file size for many applications can be medium or even small. Let them see all the data so they can make intelligent decisions. :)

That's a good suggestion. I'll try to get around to doing this soonish~ 



> 
> 
> What I haven't done is look at memory usage. Is `licofi` so much faster because it trades memory for speed? I don't have time to look into it, but that's a question.

Memory usage should be similar to lines-and-columns. Both `lines-and-columns` and `licofi` cache line start offsets when instantiated. Most of the difference in performance comes from the search algorithm, `lines-and-columns` uses naive linear search while `licofi` uses binary search.

Some of the libraries included in the benchmark don't do any caching so their memory usage will be lower, however this obviously impacts the search performance.

**Comment by vassudanagunta** [comment]
good to know! well done. 

btw, if you get just one or two big big libraries to switch to `licofi` (perhaps you do the work via PR), your npm numbers will jump and then you'll show up higher in search results and other types of visibilty, and thus spark a nice positive feedback loop.

**Pull request merged**
